apiVersion : apps/v1
kind: Deployment
metadata:
  name: mheydtpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mheydtpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: mheydtpipelinesjavascriptdocker 
    spec:
      containers:
        - name: mheydtpipelinesjavascriptdocker 
          image: stacr1.azurecr.io/mheydtpipelinesjavascriptdocker
          ports:
          - containerPort: 8080